---
title: "Lab Overview"
author:
  - name: "Zachary Cramton"
    url: "https://zachary.cramton.com"
    email: "ZCramton@colostate.edu"
toc: true
format: html
execute:
  echo: true
---

# Overview of Labs

This document provides a summary for each lab file.

# Labs

-   [Lab 01](https://zachary.cramton.com/){target="_blank"}

    -   In this lab we built personal websites using github pages. The linked file connects to the github repo for the personal site.

-   [Lab 02](./labs/lab_02.qmd){target="_blank"}

    -   In this lab we began to explore data maniplation in R.

-   [Lab 03](./labs/lab_03.qmd){target="_blank"}

    -   In this lab we used the NY-Times COVID-19 dataset to practice data manipulation, vizualization and EDA.

-   [Lab 04](./labs/lab_04.qmd){target="_blank"}

    -   In this lab we used the LTER dataset to practice statistical analysis using R.

-   [Lab 05](https://bellaconrad.github.io/ess_final_project/){target="_blank"}

    -   In this lab my group explored some potential project topics for the course project.

-   [Lab 06](./labs/lab_06.qmd){target="_blank"}

    -   In this lab we practiced building machine learning models using the CAMELS hyrological dataset.

-   [Lab 07](https://zachary.cramton.com/ess_330_project_proposal/){target="_blank"}

    -   In this lab my group outlined our course project with an abstract and exploratory data analysis (EDA).

-   [Lab 08](./labs/lab_08.qmd){target="_blank"}

    -   In this lab we practiced tuning the best machine learning model from Lab 06 using the CAMELS hyrological dataset.

-   [Lab 09](https://zachary.cramton.com/ess_330_final_project/){target="_blank"}

    -   In this lab my group completed the modeling for our project and vizualized the results.

-   [Lab 10](./labs/lab_10.qmd){target="_blank"}

    -   In this lab we work with spatial data, exploring the distance form borders in colorado and nationally.
